
public enum ProductPosType
{
    None,
    ShopMenu_1,
    ShopMenu_2,
    ShopMenu_3,
}

/// <summary>
/// 商品种类
/// </summary>
public enum ProductNameType
{
    Coins_1000,
    Coins_5000,
    Coins_10000,
    Coins_25000,
    Coins_50000,
    Coins_100000,
    Special_Offer,
    Big_Bundle,
    Super_Bundle,
    Mega_Bundle,
    Ultra_Bundle,
    Giant_Bundle,
    Champion_Bundle,
    Remove_Ads,
    Weekend_Package_Small,
    Weekend_Package_Middle,
    Weekend_Package_Big,
    Father_Package_Small,
    Father_Package_Middle,
    Father_Package_Big,
    Father_Package_Small_line,
    Father_Package_Middle_line,
    Father_Package_Big_line,
    Island_Package_Small,
    Island_Package_Middle,
    Island_Package_Big,
    Remove_Ads_New,
    Fire_Work_Small,
    Fire_Work_Middle,
    Fire_Work_Big,
    VIP_Pass,
    Super_VIP,
    Super_VIP_Discount,
    Film_One_Plus_One_Small,
    Film_One_Plus_One_Big,
    Harvest_Package_Small,
    Harvest_Package_Middle,
    Harvest_Package_Big,
    Temple_Package,
    
    PropFavor1,
    PropFavor2,
    PropFavor3,
    LevelContinueFavor1,
    LevelContinueFavor2,
    LevelContinueFavor3,
    
    Harvest_Package_Small_line,
    Harvest_Package_Middle_line,
    Harvest_Package_Big_line,

    Travel_Package_Small,
    Travel_Package_Small_1,
    Travel_Package_Small_2,
    Travel_Package_Big,
    Travel_Package_Big_1,
    Travel_Package_Big_2,

    Remove_Ads_New_1,
    Remove_Ads_New_Pro,

    Dessert_Small,
    Dessert_Middle,
    Dessert_Big,
    
    Halloween_Package_Small,
    Halloween_Package_Middle,
    Halloween_Package_Big,
    Halloween_Package_Small_line,
    Halloween_Package_Middle_line,
    Halloween_Package_Big_line,

    Coffer_Bank_1,
    Coffer_Bank_2,

    Halloween_Merge_Offer_1,
    Halloween_Merge_Offer_2,
    Halloween_Merge_Offer_3,
    Halloween_Merge_Offer_4,
    Halloween_Merge_Offer_5,
    Halloween_Merge_Offer_6,
    Halloween_Merge_Offer_7,
    Halloween_Merge_Offer_8,
    Halloween_Merge_Offer_9,

    Endless_Treasure_Package_1,
    Endless_Treasure_Package_2,
    Endless_Treasure_Package_3,
    Endless_Treasure_Package_4,
    Endless_Treasure_Package_5,

    Thanksgiving_Package_Small,
    Thanksgiving_Package_Middle,
    Thanksgiving_Package_Big,
    Thanksgiving_Package_Small_line,
    Thanksgiving_Package_Middle_line,
    Thanksgiving_Package_Big_line,

    Kitchenmatch_Package,
    
    Blackfriday_Package_Small,
    Blackfriday_Package_Middle,
    Blackfriday_Package_Big,
    Blackfriday_Package_Getall,
    
    Christmas_Package_Small,
    Christmas_Package_Middle,
    Christmas_Package_Big,
    Christmas_Package_Small_line,
    Christmas_Package_Middle_line,
    Christmas_Package_Big_line,
    
    NewYear_Package_Small,
    NewYear_Package_Middle,
    NewYear_Package_Big,
    NewYear_Package_Small_line,
    NewYear_Package_Middle_line,
    NewYear_Package_Big_line,
    
    Valentine_Package_Stage_1,
    Valentine_Package_Stage_2,
    Valentine_Package_Stage_3,

    St_Patrick_Small,
    St_Patrick_Middle,
    St_Patrick_Big,

    Holi_Small,
    Holi_Middle,
    Holi_Big,

    Easter_Package_Small,
    Easter_Package_Middle,
    Easter_Package_Big,
    Easter_Package_Small_line,
    Easter_Package_Middle_line,
    Easter_Package_Big_line,

    Frog_ad,

    Cincodemayo_Package_Small,
    Cincodemayo_Package_Middle,
    Cincodemayo_Package_Big,
    Cincodemayo_Package_Getall,

    Mother_Package_Small,
    Mother_Package_Middle,
    Mother_Package_Big,
    Mother_Package_Small_line,
    Mother_Package_Middle_line,
    Mother_Package_Big_line,

    Children_Package_Small,
    Children_Package_Middle,
    Children_Package_Big,
    Children_Package_Getall,

    Father_Package_Small_New,
    Father_Package_Middle_New,
    Father_Package_Big_New,
    Father_Package_Small_New_line,
    Father_Package_Middle_New_line,
    Father_Package_Big_New_line,

    Beach_Package_Small,
    Beach_Package_Middle,
    Beach_Package_Big,
    Beach_Package_Small_line,
    Beach_Package_Middle_line,
    Beach_Package_Big_line,

    Hard_Level_Package_1,
    Hard_Level_Package_2,
    Hard_Level_Package_3,
    Hard_Level_Package_4,
    Hard_Level_Package_5,
    Ceremony_Level_package_1,
    Ceremony_Level_package_2,
    Ceremony_Level_package_1_line,
    Ceremony_Level_package_2_line,

    Animal_Package_Small,
    Animal_Package_Middle,
    Animal_Package_Big,
    Animal_Card_Package_Small,
    Animal_Card_Package_Middle,
    Animal_Card_Package_Big,
    Animal_Package_Small_line,
    Animal_Package_Middle_line,
    Animal_Package_Big_line,
    
    Harvest_Kitchen_Package,
    
    Christmas_Card_Package_Small,
    Christmas_Card_Package_Middle,
    Christmas_Card_Package_Big,
    NewYear_Package_Small_Plus,
    NewYear_Package_Small_Plus_Free1,
    NewYear_Package_Small_Plus_Free2,
    NewYear_Card_Package_Small,
    NewYear_Card_Package_Small_Free1,
    NewYear_Card_Package_Small_Free2,
    NewYear_Package_Big_Plus,
    NewYear_Package_Big_Plus_Free1,
    NewYear_Package_Big_Plus_Free2,
    NewYear_Card_Package_Big,
    NewYear_Card_Package_Big_Free1,
    NewYear_Card_Package_Big_Free2,
    
    Valentine_Package_Small_New,
    Valentine_Package_Middle_New,
    Valentine_Package_Big_New,
    Valentine_Package_Small_line,
    Valentine_Package_Middle_line,
    Valentine_Package_Big_line,
    Valentine_Chest_Package_Big_New,
    Valentine_Card_Package_Small_New,
    Valentine_Card_Package_Middle_New,
    Valentine_Card_Package_Big_New,
    
    None,
}
