//------------------------------------------------------------
// Auto generated by tool, please do not modify it directly.
// Generate From MergeTheme.xlsx
// Generate Time:2024/11/11 16:14:54
//------------------------------------------------------------


public enum MergeTheme
{
	None = 0,
	Halloween = 1, // 万圣节
	Christmas = 2, // 圣诞节
	StPatricks = 3, // 圣帕特里克节
	LoveGiftBattle = 4, //约会大作战
	DigTreasure = 5, //挖宝
	Cinderella = 6, //灰姑娘
    Dog = 7, //测试
}

