
/// <summary>
/// TextMeshPro材质球预设名称
/// </summary>
public enum MaterialPresetName
{
    None,
    Title_Blue,
    Title_Red,
    Title_Purple,
    Btn_Yellow,
    Btn_Green,
    Btn_Red,
    Btn_Blue,
    Top_Caption,
    Bar_Black,
    Cou_Blue,
    Cou_Red,
    Cou_Purple,
    Btn_Grey,
    Msg_Whtie,
    Pass_Yellow,
    Pass_Blue,
    Shop_Purple,
    Text_Blue,
    Text_Blue2,
    Btn_Team,
    Btn_Green2,
    Shop_Green,
    Shop_Brown,
    Shop_Purple2,
    Text_Orange,
    Text_Orange1,
    Btn_Red2,
    Text_Black_30,
    Text_Pink,
    TurnTable_Blue,
    
    Comb_OutLine_Green,
    Comb_OutLine_Blue,
    Comb_OutLine_Purple,
    Comb_OutLine_Orange,
    Comb_OutLine_Red,
    
    Text_Black_Outline_Underlay,
    Title_Yellow,
    Title_Bronze,
    Title_Silver,
    Title_Gold,
    Title_Supreme,
    
    LevelNormal,
    LevelHard,
    LevelSurpHard,
    
    Btn_Purple,
    Btn_White,
    Shop_Blue,
    Lava_Pink,
    Shop_Red,
    NewStory,
    Title_Red2,
    Title_Purple2,
    Btn_Blue2,
    Comb_OutLine_Orange2,
    New_Brown,

    OceanMerge,
    OceanMerge2,
    OceanMerge3,
    Light_Purple,
    Light_Green,
    Gift_Purple,
    Critical_Red,
    Critical_Blue,
    Bottom_Blue,
    Title_Love,
    Inside_Love,
    
    Card_Shadow,
    Card_White,
    Card_Green,
    Card_LightGreen,
}
